// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    // Vue Router Components
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];

    // Vuetify Components
    VApp: typeof import('vuetify/lib')['VApp'];
    VMain: typeof import('vuetify/lib')['VMain'];
    VAppBar: typeof import('vuetify/lib')['VAppBar'];
    
    VSpacer: typeof import('vuetify/lib')['VSpacer'];
    VContainer: typeof import('vuetify/lib')['VContainer'];
    VDivider: typeof import('vuetify/lib')['VDivider'];
    VBtn: typeof import('vuetify/lib')['VBtn'];
  }
}

export {}
